---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "9153"
    prometheus.io/scrape: "true"
    metallb.universe.tf/allow-shared-ip: "dns-allow-tcp-udp-on-same-port"
  name: coredns-lb-tcp
  namespace: kube-system
spec:
  selector:
    k8s-app: kube-dns
  type: LoadBalancer
  loadBalancerIP: 172.17.255.10
  ports:
    - name: dns-tcp
      protocol: TCP
      port: 53
      targetPort: 53
    - name: dns-metrics
      protocol: TCP
      port: 9153
      targetPort: 9153
