# https://github.com/prometheus-operator/kube-prometheus/blob/master/manifests/node-exporter-serviceAccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-exporter
  namespace: monitoring
